# Generated by Django 4.2.1 on 2024-07-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('film_name', models.CharField(max_length=300, null=True)),
                ('update', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
